"""Add start_date and end_date to Group

Revision ID: 531dd5f27307
Revises: bfcebc4e5f31
Create Date: 2026-05-06 16:40:11.362177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531dd5f27307'
down_revision = 'bfcebc4e5f31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
