"""Add split_type to Expense and create ExpenseSplit table

Revision ID: ce5c9057a58a
Revises: 531dd5f27307
Create Date: 2026-05-06 17:09:22.261399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5c9057a58a'
down_revision = '531dd5f27307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('share_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('expense_id', 'user_id', name='unique_expense_user_split')
    )
    
    # SQLite-safe: add nullable first, then set default and make NOT NULL
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_type', sa.String(length=20), nullable=True))
    op.execute("UPDATE expenses SET split_type = 'equal'")
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('split_type', existing_type=sa.String(length=20), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('split_type')

    op.drop_table('expense_splits')
    # ### end Alembic commands ###
